// <auto-generated />
namespace DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class mod_gendertype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mod_gendertype));
        
        string IMigrationMetadata.Id
        {
            get { return "202401081617234_mod_gendertype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
